outbox:
  thread-pool-size: 8
  tables:
    auto-create: true
  publisher:
    sender:
      type: kafka
    defaults:
      batch-size: 100
      initial-delay: 2m
      fixed-delay: 2s
      max-retries: 3
      backoff:
        delay: 5s
        multiplier: 10
    events:
      account-delete:
        topic: accounts-deleted
        fixed-delay: 1m
      rating-update:
        topic: ratings-updated
      validate-review:
        topic: reviews-for-validate
        fixed-delay: 10s
      validate-specialist:
        topic: specialist-for-validate
        fixed-delay: 2m
      validate-specialist-action:
        topic: specialists-action-for-validate
      validate-type:
        topic: types-for-validate
        fixed-delay: 10m
    clean-up:
      fixed-delay: 3s
    dlq:
      enabled: true

  consumer:
    enabled: true
    cache:
      enabled: true
      cache-name: outbox-consumed-events
    clean-up:
      ttl: 24h
      fixed-delay: 1m
